######################################################################
# Automatically generated by qmake (3.0) Sun Jan 19 05:19:36 2014
######################################################################

TEMPLATE = lib
CONFIG += debug c++11
TARGET = html_processing
INCLUDEPATH += .
DEFINES += HTML_PROCESSING_LIBRARY
QT += webkit webkitwidgets

# Input
HEADERS += html_processing.h html_processing_inc.h webpage.h
SOURCES += html_processing.cpp html_processing_inc.cpp
